#!/bin/bash

set -e

########
# Constants
########

readonly NL=$'\n'
readonly TAB=$'\t'


########
# Parse command line options
########

function print_usage {
  echo "usage: treehash [-b|--block <size>] [-a|--alg <alg>] [-v|--verbose <level>] <file>"
  echo ""
  echo "Calculates the top level hash of a Merkel tree (tree hash) built from equal sized chunks of a file."
  echo ""
  echo "    --block    size of the leave data blocks in bytes, defaults to 1M."
  echo "               can be postfixed with K, M, G, T, P, E, k, m, g, t, p, or e,"
  echo "               see the '--block' option of the 'parallel' command for details."
  echo "    --alg      hash algorithm to use, defaults to 'sha256'. Supported"
  echo "               algorithms are the ones supported by 'openssl dgst'"
  echo "    --verbose  print diagnostic messages to stderr if level is large then 0"
}

arg_positional=()
while [[ $# -gt 0 ]]; do
  key="$1"

  case $key in
      -h|--help)
      print_usage
      exit 0
      ;;
      -b|--block)
      arg_block="$2"
      shift # past argument
      shift # past value
      ;;
      -v|--verbose)
      arg_log="$2"
      shift # past argument
      shift # past value
      ;;
      -a|--alg)
      arg_alg="$2"
      shift # past argument
      shift # past value
      ;;
      *)    # unknown option
      arg_positional+=("$1") # save it in an array for later
      shift # past argument
      ;;
  esac
done
set -- "${arg_positional[@]}" # restore positional parameters

readonly log=${arg_log:-0}
readonly block_size="${arg_block:-1M}"
readonly hash_alg="${arg_alg:-sha256}"


##########
# Utility functions
##########

function combine_hash {
  # Convert hex format to binary, concat and hash
  cat <(echo -n "$1" | xxd -r -p) <(echo -n "$2" | xxd -r -p) \
      | openssl dgst -"$hash_alg" -hex | cut -f 2 -d ' '
}


############
# Calculate tree hash iterating stdin
############

function calculate_root_hash {
  local max_depth="$1"

  # Base case: read chunk from stdin and calculate leave hash
  if (( $max_depth == 0 )); then
    local hash
    read hash && hash="${hash##* }"
    if [[ -z "$hash" ]]; then
      (($log > 0)) && >&2 echo "Input exhausted" || :
      exit 0
    fi

    (($log > 0)) && >&2 echo "Read $hash" || :
    echo -n "$hash"
    exit 0
  fi

  # Recurse to calculate left/right child hashes and combine them
  local -r left=$(calculate_root_hash $(($max_depth - 1)))
  if [[ -z "$left" ]]; then
    (($log > 0)) && >&2 echo "Terminate: no left root"|| :
    exit 0
  fi
  (($log > 0)) && >&2 echo "Left root: $left" || :

  local right=$(calculate_root_hash $(($max_depth - 1)))
  if [[ -z "$right" ]]; then
    (($log > 0)) && >&2 echo "Terminate: no right root" || :
    echo -n "$left"
    exit 0
  fi
  (($log > 0)) && >&2 echo "Right root: $right" || :

  combine_hash "$left" "$right"
}

function calculate_hash {
  local left="$1"
  local level="$2"

  # Initialize
  if [[ -z "$left" ]]; then
    local first="$(calculate_root_hash 0)"
    if [[ -z "$first" ]]; then
      (($log > 0)) && >&2 echo "No input" || :
      exit 0
    fi

    (($log > 0)) && >&2 echo "Initialize with $first" || :
    calculate_hash "$first" 0
    exit 0
  fi

  (($log > 0)) && >&2 echo "Calculate hash at level $level" || :

  # Calculate right child and recurse to calculate the next level
  local right=$(calculate_root_hash $level)
  if [[ -z "$right" ]]; then
    (($log > 0)) && >&2 echo "Terminate: no right child, return left: $left" || :
    echo -n "$left"
    exit 0
  fi

  (($log > 0)) && >&2 echo "Left child ($level): $left" || :
  (($log > 0)) && >&2 echo "Right child ($level): $right" || :

  combined=$(combine_hash "$left" "$right")
  (($log > 0)) && >&2 echo "Combined hash ($level): $right" || :

  calculate_hash $combined $(($level + 1))
}


########
# Split stdin into chunks and feed into the hash algorithm
########

input_file="$1"

(($log > 0)) && >&2 echo "Calculate hash for $input_file" || :

cat $input_file \
  | parallel --no-notice --pipe --block $block_size --recend '' -k \
      "openssl dgst -$hash_alg -hex" \
  | calculate_hash "" 0

# Terminate with newline
echo ""
